### ISSUE TITLE
Color selection should be indicated in the console

### ISSUE THREAD

**Issue by iostream72** [perfectsquircle/sqlinjector#9]
I use colors to warn me when I'm connected to a test or production database. It would be nice if the color I chose for a connection was indicated in the query console somewhere prominently. Something like this:

![image](https://cloud.githubusercontent.com/assets/2018544/10370690/3e5d8268-6d9d-11e5-8c96-cd59a34cb59e.png)

or

![image](https://cloud.githubusercontent.com/assets/2018544/10370698/4e480f54-6d9d-11e5-9133-7759215eee13.png)

**Comment by perfectsquircle** [comment]
This is done on develop, just need to publish to npm.

**Comment by iostream72** [comment]
Just pulled the update, looks awesome. Thanks!
